/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolIdRouteImport } from './routes/tool.$id'
import { Route as GameSudokuRouteImport } from './routes/game.sudoku'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolIdRoute = ToolIdRouteImport.update({
  id: '/tool/$id',
  path: '/tool/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSudokuRoute = GameSudokuRouteImport.update({
  id: '/game/sudoku',
  path: '/game/sudoku',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/game/sudoku': typeof GameSudokuRoute
  '/tool/$id': typeof ToolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/game/sudoku': typeof GameSudokuRoute
  '/tool/$id': typeof ToolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/game/sudoku': typeof GameSudokuRoute
  '/tool/$id': typeof ToolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites' | '/game/$gameId' | '/game/sudoku' | '/tool/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/game/$gameId' | '/game/sudoku' | '/tool/$id'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/game/$gameId'
    | '/game/sudoku'
    | '/tool/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  GameGameIdRoute: typeof GameGameIdRoute
  GameSudokuRoute: typeof GameSudokuRoute
  ToolIdRoute: typeof ToolIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$id': {
      id: '/tool/$id'
      path: '/tool/$id'
      fullPath: '/tool/$id'
      preLoaderRoute: typeof ToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/sudoku': {
      id: '/game/sudoku'
      path: '/game/sudoku'
      fullPath: '/game/sudoku'
      preLoaderRoute: typeof GameSudokuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  GameGameIdRoute: GameGameIdRoute,
  GameSudokuRoute: GameSudokuRoute,
  ToolIdRoute: ToolIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
